# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_3/design_3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_0_0/design_3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_0_0 || ORIG_REF_NAME==design_3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_1_0/design_3_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_1_0 || ORIG_REF_NAME==design_3_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_2_0/design_3_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_2_0 || ORIG_REF_NAME==design_3_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_3_0/design_3_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_3_0 || ORIG_REF_NAME==design_3_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_4_0/design_3_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_4_0 || ORIG_REF_NAME==design_3_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_5_0/design_3_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_5_0 || ORIG_REF_NAME==design_3_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_6_0/design_3_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_6_0 || ORIG_REF_NAME==design_3_axi_gpio_6_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_7_0/design_3_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_7_0 || ORIG_REF_NAME==design_3_axi_gpio_7_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_private_key_RSA_0_0/design_3_private_key_RSA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_private_key_RSA_0_0 || ORIG_REF_NAME==design_3_private_key_RSA_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_proc_sys_reset_0_1/design_3_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_proc_sys_reset_0_1 || ORIG_REF_NAME==design_3_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_processing_system7_0_1/design_3_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_processing_system7_0_1 || ORIG_REF_NAME==design_3_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xbar_1/design_3_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_xbar_1 || ORIG_REF_NAME==design_3_xbar_1} -quiet] -quiet

# IP: bd/design_3/ip/design_3_ps7_0_axi_periph_0/design_3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rsa_decrypt_0_0/design_3_rsa_decrypt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_rsa_decrypt_0_0 || ORIG_REF_NAME==design_3_rsa_decrypt_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rsa_encrypt_0_0/design_3_rsa_encrypt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_rsa_encrypt_0_0 || ORIG_REF_NAME==design_3_rsa_encrypt_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_axi_gpio_8_0/design_3_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_axi_gpio_8_0 || ORIG_REF_NAME==design_3_axi_gpio_8_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_3_auto_pc_0 || ORIG_REF_NAME==design_3_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Miruna/Documents/POLI/an3/SSC/proiectCraciun/projectCraciun/projectCraciun.gen/sources_1/bd/design_3/design_3_ooc.xdc
