# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Miruna/Documents/POLI/an3/SSC/proiectCraciun/projectCraciun/projectCraciun.srcs/sources_1/bd/design_3/ip/design_3_processing_system7_0_1/design_3_processing_system7_0_1.xci
# IP: The module: 'design_3_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Miruna/Documents/POLI/an3/SSC/proiectCraciun/projectCraciun/projectCraciun.gen/sources_1/bd/design_3/ip/design_3_processing_system7_0_1/design_3_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Miruna/Documents/POLI/an3/SSC/proiectCraciun/projectCraciun/projectCraciun.srcs/sources_1/bd/design_3/ip/design_3_processing_system7_0_1/design_3_processing_system7_0_1.xci
# IP: The module: 'design_3_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Miruna/Documents/POLI/an3/SSC/proiectCraciun/projectCraciun/projectCraciun.gen/sources_1/bd/design_3/ip/design_3_processing_system7_0_1/design_3_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
